### ISSUE TITLE
Filter tab enhancements

### ISSUE THREAD

**Issue by jaelafield** [UWSocialComputing/wander-code#19]
Styling:
- New design @noaferman 
- Much CSS @katherinemurphy2001 

Design components:
- Color association with pins
- New filters (price, anything else?)
- Select/deselect all

Functionality: @katherinemurphy2001 
- Make filters auto apply (no button click needed)
- Make component collapsable

**Comment by katherinemurphy2001** [comment]
debug filter event type onClick
